export const SERVER_END_POINTS = {
  USER_SIGNUP: "/user/signup",
  USER_VERIFICATION: "/user/account/verification",
  USER_RESEND_VERIFICATION: "/user/resend/account/verification",
  USER_LOGIN: "/user/login",
  USER_GOOGLE: "/user/google",
  FORGET_PASSWORD: "/user/forgot/password",
  RESET_PASSWORD: "/user/reset/password",
  SET_PASSWORD: "/user/reset/password",
  CHANGE_PASSWORD: "/user/change/password",
  USER_PROFILE: "/user/profile",
  EDIT_USER: "/user/profile",
  USER_BLOG: "/user/blog",
  BLOG_WISHLIST_TOGGLE: "/user/blog/wishlist/toggle",
  CATEGORIES: "/category",
  WISHLIST_CATEGORIES: "/category/wishlist",
};
